name: aa
description: "A new Flutter project."
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"  # SDK 버전 범위 지정

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase dependencies
  firebase_core: ^2.15.0
  firebase_auth: ^4.16.0  # 버전 변경

  # Calendar dependency
  flutter_calendar_carousel: ^2.3.1

  # HTTP 요청을 위한 패키지
  http: ^1.2.2

  # 날짜 포맷팅을 위한 패키지
  intl: ^0.19.0

  # Google Maps 패키지
  google_maps_flutter: ^2.9.0  # 최신 버전으로 변경

  # Geolocator 패키지
  geolocator: ^9.0.2  # 최신 버전으로 변경

  # Permission Handler 패키지
  permission_handler: ^11.3.1  # 최신 버전으로 유지

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

